### ISSUE TITLE
[BUG] When i open my server occurs that

### ISSUE THREAD

**Issue by ElFlambMC** [twizmwazin/CardinalPGM#283]
[17:48:53] [Server thread/INFO]: Starting minecraft server version 1.7.10
[17:48:53] [Server thread/INFO]: Loading properties
[17:48:53] [Server thread/INFO]: Default game type: SURVIVAL
[17:48:53] [Server thread/INFO]: Generating keypair
[17:48:54] [Server thread/INFO]: Starting Minecraft server on *:25565
[17:48:55] [Server thread/INFO]: This server is running SportBukkit version git-SportBukkit-1.7.9-R0.2-104-g95ec589 (MC: 1.7.10) (Implementing API version 1.7.10-R0.1-SNAPSHOT)
[17:48:55] [Server thread/INFO]: [CardinalPGM] Loading Cardinal v1.0-SNAPSHOT-git-CardinalPGM-unknown
[17:48:56] [Server thread/INFO]: Preparing level "world"
[17:48:56] [Server thread/INFO]: Preparing start region for level 0 (Seed: -8636621234183906877)
[17:48:56] [Thread-7/WARN]: Could not get information about this CraftBukkit version; perhaps you are running a custom one?: FileNotFoundException
[17:48:57] [Server thread/INFO]: Preparing spawn area: 16%
[17:48:57] [Thread-7/WARN]: Could not get latest artifact information: FileNotFoundException
[17:48:58] [Server thread/INFO]: Preparing spawn area: 52%
[17:48:59] [Server thread/INFO]: Preparing spawn area: 97%
[17:48:59] [Server thread/INFO]: Preparing start region for level 1 (Seed: -8636621234183906877)
[17:49:00] [Server thread/INFO]: Preparing spawn area: 40%
[17:49:01] [Server thread/INFO]: Preparing spawn area: 93%
[17:49:01] [Server thread/INFO]: Preparing start region for level 2 (Seed: -8636621234183906877)
[17:49:02] [Server thread/INFO]: [CardinalPGM] Enabling Cardinal v1.0-SNAPSHOT-git-CardinalPGM-unknown
[17:49:02] [Server thread/ERROR]: Error occurred while enabling Cardinal v1.0-SNAPSHOT-git-CardinalPGM-unknown (Is it up to date?)
java.lang.NoClassDefFoundError: org/apache/commons/lang3/tuple/ImmutablePair
	at in.twizmwaz.cardinal.rotation.Rotation.refreshRepo(Rotation.java:59) ~[?:?]
	at in.twizmwaz.cardinal.rotation.Rotation.<init>(Rotation.java:34) ~[?:?]
	at in.twizmwaz.cardinal.GameHandler.<init>(GameHandler.java:31) ~[?:?]
	at in.twizmwaz.cardinal.Cardinal.onEnable(Cardinal.java:151) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[sportbukkit.jar:git-SportBukkit-1.7.9-R0.2-104-g95ec589]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:324) [sportbukkit.jar:git-SportBukkit-1.7.9-R0.2-104-g95ec589]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [sportbukkit.jar:git-SportBukkit-1.7.9-R0.2-104-g95ec589]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:460) [sportbukkit.jar:git-SportBukkit-1.7.9-R0.2-104-g95ec589]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:394) [sportbukkit.jar:git-SportBukkit-1.7.9-R0.2-104-g95ec589]
	at net.minecraft.server.v1_7_R4.MinecraftServer.n(MinecraftServer.java:362) [sportbukkit.jar:git-SportBukkit-1.7.9-R0.2-104-g95ec589]
	at net.minecraft.server.v1_7_R4.MinecraftServer.g(MinecraftServer.java:336) [sportbukkit.jar:git-SportBukkit-1.7.9-R0.2-104-g95ec589]
	at net.minecraft.server.v1_7_R4.MinecraftServer.a(MinecraftServer.java:292) [sportbukkit.jar:git-SportBukkit-1.7.9-R0.2-104-g95ec589]
	at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:189) [sportbukkit.jar:git-SportBukkit-1.7.9-R0.2-104-g95ec589]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:446) [sportbukkit.jar:git-SportBukkit-1.7.9-R0.2-104-g95ec589]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [sportbukkit.jar:git-SportBukkit-1.7.9-R0.2-104-g95ec589]
Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang3.tuple.ImmutablePair
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_31]
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_31]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_31]
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_31]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:77) ~[sportbukkit.jar:git-SportBukkit-1.7.9-R0.2-104-g95ec589]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:62) ~[sportbukkit.jar:git-SportBukkit-1.7.9-R0.2-104-g95ec589]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_31]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_31]
	... 15 more
[17:49:02] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[17:49:02] [Server thread/INFO]: Done (6,608s)! For help, type "help" or "?"

**Comment by ElFlambMC** [comment]
Solved

**Comment by ElFlambMC** [comment]
1.8 sportbukkit its ok with no bugs
