### ISSUE TITLE
Error opening the server

### ISSUE THREAD

**Issue by 2000thehecf1** [twizmwazin/CardinalPGM#403]
My server doesn't recognize Cardinal plugin, I saw a tutorial and I did everything like in the video, but it doesn't work :(

Here's the error:

[12:40:20] [Server thread/ERROR]: Could not load 'plugins\CardinalPGM-1.0-SNAPSHOT.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: in/twizmwaz/cardinal/Cardinal : Unsupported major.minor version 51.0
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[sportbukkit.jar:git-SportBukkit-c31220d]
at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:328) ~[sportbukkit.jar:git-SportBukkit-c31220d]
at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [sportbukkit.jar:git-SportBukkit-c31220d]
at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugins(CraftServer.java:292) [sportbukkit.jar:git-SportBukkit-c31220d]
at org.bukkit.craftbukkit.v1_8_R1.CraftServer.<init>(CraftServer.java:254) [sportbukkit.jar:git-SportBukkit-c31220d]
at net.minecraft.server.v1_8_R1.PlayerList.<init>(PlayerList.java:71) [sportbukkit.jar:git-SportBukkit-c31220d]
at net.minecraft.server.v1_8_R1.DedicatedPlayerList.<init>(SourceFile:14) [sportbukkit.jar:git-SportBukkit-c31220d]
at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:133) [sportbukkit.jar:git-SportBukkit-c31220d]
at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:490) [sportbukkit.jar:git-SportBukkit-c31220d]
at java.lang.Thread.run(Unknown Source) [?:1.6.0_35]
Caused by: java.lang.UnsupportedClassVersionError: in/twizmwaz/cardinal/Cardinal : Unsupported major.minor version 51.0
at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.6.0_35]
at java.lang.ClassLoader.defineClassCond(Unknown Source) ~[?:1.6.0_35]
at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.6.0_35]
at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.6.0_35]
at java.net.URLClassLoader.defineClass(Unknown Source) ~[?:1.6.0_35]
at java.net.URLClassLoader.access$000(Unknown Source) ~[?:1.6.0_35]
at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.6.0_35]
at java.security.AccessController.doPrivileged(Native Method) ~[?:1.6.0_35]
at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.6.0_35]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:77) ~[sportbukkit.jar:git-SportBukkit-c31220d]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:62) ~[sportbukkit.jar:git-SportBukkit-c31220d]
at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.6.0_35]
at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.6.0_35]
at java.lang.Class.forName0(Native Method) ~[?:1.6.0_35]
at java.lang.Class.forName(Unknown Source) ~[?:1.6.0_35]
at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:40) ~[sportbukkit.jar:git-SportBukkit-c31220d]
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[sportbukkit.jar:git-SportBukkit-c31220d]
... 9 more

**Comment by twizmwazin** [comment]
Install Java 7 or newer

**Comment by 2000thehecf1** [comment]
@twizmwazin Thanks!!!!! :D
