### ISSUE TITLE
NPE when loading plugin on server

### ISSUE THREAD

**Issue by CaptainElliott** [twizmwazin/CardinalPGM#45]
```
8:07:30] [Server thread/INFO]: [CardinalPGM] Enabling Cardinal v1.0-DEV
[08:07:30] [Server thread/ERROR]: Error occurred while enabling Cardinal v1.0-DEV (Is it up to date?)
java.lang.NullPointerException
	at in.twizmwaz.cardinal.rotation.Rotation.refreshRepo(Rotation.java:44) ~[?:?]
	at in.twizmwaz.cardinal.rotation.Rotation.<init>(Rotation.java:31) ~[?:?]
	at in.twizmwaz.cardinal.GameHandler.<init>(GameHandler.java:29) ~[?:?]
	at in.twizmwaz.cardinal.Cardinal.onEnable(Cardinal.java:64) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:250) ~[craftbukkit.jar:git-Bukkit-1.7.2-R0.3-2-g85f5776-b3024jnks]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:324) [craftbukkit.jar:git-Bukkit-1.7.2-R0.3-2-g85f5776-b3024jnks]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [craftbukkit.jar:git-Bukkit-1.7.2-R0.3-2-g85f5776-b3024jnks]
	at org.bukkit.craftbukkit.v1_7_R1.CraftServer.loadPlugin(CraftServer.java:439) [craftbukkit.jar:git-Bukkit-1.7.2-R0.3-2-g85f5776-b3024jnks]
	at org.bukkit.craftbukkit.v1_7_R1.CraftServer.enablePlugins(CraftServer.java:375) [craftbukkit.jar:git-Bukkit-1.7.2-R0.3-2-g85f5776-b3024jnks]
	at net.minecraft.server.v1_7_R1.MinecraftServer.m(MinecraftServer.java:342) [craftbukkit.jar:git-Bukkit-1.7.2-R0.3-2-g85f5776-b3024jnks]
	at net.minecraft.server.v1_7_R1.MinecraftServer.g(MinecraftServer.java:319) [craftbukkit.jar:git-Bukkit-1.7.2-R0.3-2-g85f5776-b3024jnks]
	at net.minecraft.server.v1_7_R1.MinecraftServer.a(MinecraftServer.java:275) [craftbukkit.jar:git-Bukkit-1.7.2-R0.3-2-g85f5776-b3024jnks]
	at net.minecraft.server.v1_7_R1.DedicatedServer.init(DedicatedServer.java:175) [craftbukkit.jar:git-Bukkit-1.7.2-R0.3-2-g85f5776-b3024jnks]
	at net.minecraft.server.v1_7_R1.MinecraftServer.run(MinecraftServer.java:424) [craftbukkit.jar:git-Bukkit-1.7.2-R0.3-2-g85f5776-b3024jnks]
	at net.minecraft.server.v1_7_R1.ThreadServerApplication.run(SourceFile:617) [craftbukkit.jar:git-Bukkit-1.7.2-R0.3-2-g85f5776-b3024jnks]
```

Will personally look into it soon

**Comment by ItzWid13** [comment]
To Run This plugin you need  the last version of SportBukkit :dancer: 
that can be downloaded here https://repo.oc.tc/content/repositories/snapshots/tc/oc/sportbukkit/1.7.10-R0.1-SNAPSHOT/

**Comment by CaptainElliott** [comment]
Same error

**Comment by ItzWid13** [comment]
You need a rotation.txt file with the rotation that you wish

**Comment by CaptainElliott** [comment]
Yeah, but the plugin should create that file if it does not already exist

**Comment by ItzWid13** [comment]
You need to create it xd

**Comment by CaptainElliott** [comment]
I don't see a reason why the user should create it. They are going to have no clue what the error means

**Comment by ItzWid13** [comment]
i create it and the plugin works perfectly

**Comment by CaptainElliott** [comment]
Yes, but a normal person would no know to create it

**Comment by ItzWid13** [comment]
ok, now it works?
