### ISSUE TITLE
When i load my map it appears this in my log

### ISSUE THREAD

**Issue by xDofah** [twizmwazin/CardinalPGM#495]
[14:05:01 INFO]: Next map set to Snowy Wools
cycle 0
[14:05:03 INFO]: Preparing start region for level 4 (Seed: 6030536467267057983)
[14:05:03 WARN]: java.lang.ArrayIndexOutOfBoundsException: 2
[14:05:03 WARN]:        at in.twizmwaz.cardinal.module.modules.regions.parsers.CylinderParser.<init>(CylinderParser.java:19)
[14:05:03 WARN]:        at in.twizmwaz.cardinal.module.modules.regions.RegionModuleBuilder.getRegion(RegionModuleBuilder.java:68)
[14:05:03 WARN]:        at in.twizmwaz.cardinal.module.modules.regions.RegionModuleBuilder.getRegion(RegionModuleBuilder.java:133)
[14:05:03 WARN]:        at in.twizmwaz.cardinal.module.modules.spawn.SpawnModuleBuilder.load(SpawnModuleBuilder.java:103)
[14:05:03 WARN]:        at in.twizmwaz.cardinal.module.ModuleFactory.build(ModuleFactory.java:181)
[14:05:03 WARN]:        at in.twizmwaz.cardinal.match.Match.registerModules(Match.java:52)
[14:05:03 WARN]:        at in.twizmwaz.cardinal.GameHandler.cycleAndMakeMatch(GameHandler.java:43)
[14:05:03 WARN]:        at in.twizmwaz.cardinal.module.modules.cycleTimer.CycleTimerModule.run(CycleTimerModule.java:44)
[14:05:03 WARN]:        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:53)
[14:05:03 WARN]:        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349)
[14:05:03 WARN]:        at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:666)
[14:05:03 WARN]:        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:284)
[14:05:03 WARN]:        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:611)
[14:05:03 WARN]:        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:521)
[14:05:03 WARN]:        at java.lang.Thread.run(Thread.java:745)
[14:05:03 INFO]: [CardinalPGM] 100 modules loaded.
[14:05:03 INFO]: Cycled to Snowy Wools

XML is in good state,i

**Comment by twizmwazin** [comment]
There is an issue with one of your cylinder regions. Make sure you are following the format outlined [here](https://docs.oc.tc/modules/regions).
