### ISSUE TITLE
Unable to load Plugin

### ISSUE THREAD

**Issue by Ster13** [twizmwazin/CardinalPGM#539]
[00:32:01 INFO]: Starting minecraft server version 1.8
[00:32:01 INFO]: Loading properties
[00:32:01 INFO]: Default game type: SURVIVAL
[00:32:01 INFO]: Generating keypair
[00:32:01 INFO]: Starting Minecraft server on *:25565
[00:32:02 INFO]: This server is running SportBukkit version git-SportBukkit-715f5f8 (MC: 1.8) (Implementing API version 1.8-R0.1-SNAPSHOT)
[00:32:02 ERROR]: Could not load 'plugins/CardinalPGM-1.0-SNAPSHOT.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: in/twizmwaz/cardinal/Cardinal : Unsupported major.minor version 51.0
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[sportbukkit.jar:git-SportBukkit-715f5f8]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:328) ~[sportbukkit.jar:git-SportBukkit-715f5f8]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [sportbukkit.jar:git-SportBukkit-715f5f8]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugins(CraftServer.java:292) [sportbukkit.jar:git-SportBukkit-715f5f8]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.<init>(CraftServer.java:254) [sportbukkit.jar:git-SportBukkit-715f5f8]
	at net.minecraft.server.v1_8_R1.PlayerList.<init>(PlayerList.java:71) [sportbukkit.jar:git-SportBukkit-715f5f8]
	at net.minecraft.server.v1_8_R1.DedicatedPlayerList.<init>(SourceFile:14) [sportbukkit.jar:git-SportBukkit-715f5f8]
	at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:133) [sportbukkit.jar:git-SportBukkit-715f5f8]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:490) [sportbukkit.jar:git-SportBukkit-715f5f8]
	at java.lang.Thread.run(Thread.java:695) [?:1.6.0_65]
Caused by: java.lang.UnsupportedClassVersionError: in/twizmwaz/cardinal/Cardinal : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.6.0_65]
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637) ~[?:1.6.0_65]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621) ~[?:1.6.0_65]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141) ~[?:1.6.0_65]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283) ~[?:1.6.0_65]
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58) ~[?:1.6.0_65]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197) ~[?:1.6.0_65]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.6.0_65]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190) ~[?:1.6.0_65]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:77) ~[sportbukkit.jar:git-SportBukkit-715f5f8]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:62) ~[sportbukkit.jar:git-SportBukkit-715f5f8]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306) ~[?:1.6.0_65]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247) ~[?:1.6.0_65]
	at java.lang.Class.forName0(Native Method) ~[?:1.6.0_65]
	at java.lang.Class.forName(Class.java:249) ~[?:1.6.0_65]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:40) ~[sportbukkit.jar:git-SportBukkit-715f5f8]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[sportbukkit.jar:git-SportBukkit-715f5f8]
	... 9 more
[00:32:02 INFO]: [WorldEdit] Loading WorldEdit v6.0;3342-78f975b9
[00:32:02 INFO]: Preparing level "world"
[00:32:02 INFO]: Preparing start region for level 0 (Seed: 3493880480819380481)
[00:32:03 INFO]: Preparing spawn area: 29%
[00:32:04 INFO]: Preparing spawn area: 65%
[00:32:05 INFO]: Preparing start region for level 1 (Seed: 3493880480819380481)
[00:32:06 INFO]: Preparing spawn area: 52%
[00:32:07 INFO]: Preparing start region for level 2 (Seed: 3493880480819380481)
[00:32:07 INFO]: [WorldEdit] Enabling WorldEdit v6.0;3342-78f975b9
[00:32:08 INFO]: [WorldEdit] Default configuration file written: config.yml
[00:32:08 INFO]: WEPIF: Updated config file
[00:32:08 INFO]: WEPIF: Using the Bukkit Permissions API.
[00:32:08 ERROR]: Error occurred while enabling WorldEdit v6.0;3342-78f975b9 (Is it up to date?)
java.lang.ClassCastException: java.util.jar.JarFile cannot be cast to java.io.Closeable
	at com.sk89q.worldedit.util.io.Closer.close(Closer.java:153) ~[?:?]
	at com.sk89q.worldedit.bukkit.adapter.BukkitImplLoader.addFromJar(BukkitImplLoader.java:104) ~[?:?]
	at com.sk89q.worldedit.bukkit.WorldEditPlugin.loadAdapter(WorldEditPlugin.java:142) ~[?:?]
	at com.sk89q.worldedit.bukkit.WorldEditPlugin.onEnable(WorldEditPlugin.java:119) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[sportbukkit.jar:git-SportBukkit-715f5f8]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:327) [sportbukkit.jar:git-SportBukkit-715f5f8]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [sportbukkit.jar:git-SportBukkit-715f5f8]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:346) [sportbukkit.jar:git-SportBukkit-715f5f8]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:318) [sportbukkit.jar:git-SportBukkit-715f5f8]
	at net.minecraft.server.v1_8_R1.MinecraftServer.q(MinecraftServer.java:404) [sportbukkit.jar:git-SportBukkit-715f5f8]
	at net.minecraft.server.v1_8_R1.MinecraftServer.k(MinecraftServer.java:372) [sportbukkit.jar:git-SportBukkit-715f5f8]
	at net.minecraft.server.v1_8_R1.MinecraftServer.a(MinecraftServer.java:327) [sportbukkit.jar:git-SportBukkit-715f5f8]
	at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:190) [sportbukkit.jar:git-SportBukkit-715f5f8]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:490) [sportbukkit.jar:git-SportBukkit-715f5f8]
	at java.lang.Thread.run(Thread.java:695) [?:1.6.0_65]
[00:32:08 INFO]: Server permissions file permissions.yml is empty, ignoring it
[00:32:08 INFO]: Done (6.274s)! For help, type "help" or "?"

**Comment by twizmwazin** [comment]
Update to Java 7 or newer

**Comment by Ster13** [comment]
Thanks!

**Comment by Ster13** [comment]
I updated to Java 8 and it's still not working

**Comment by twizmwazin** [comment]
@Ster13 You need to set java 8 as your default java version.

**Comment by Ster13** [comment]
How am I supposed to do that if I'm using a Mac

**Comment by twizmwazin** [comment]
Try google

**Comment by SungMatt** [comment]
@Ster13 Mac user here: you can use [jenv](http://www.jenv.be) to manage your java versions. Just set it to 1.8 as your default in your server folder.
