### ISSUE TITLE
Unable to do anything with the plugin

### ISSUE THREAD

**Issue by Tranziii** [twizmwazin/CardinalPGM#545]
Here are the logs.

[13:38:41 INFO]: Starting minecraft server version 1.8
[13:38:41 INFO]: Loading properties
[13:38:41 INFO]: Default game type: SURVIVAL
[13:38:41 INFO]: Generating keypair
[13:38:41 INFO]: Starting Minecraft server on *:25565
[13:38:42 INFO]: This server is running SportBukkit version git-SportBukkit-715f5f8 (MC: 1.8) (Implementing API version 1.8-R0.1-SNAPSHOT)
[13:38:42 INFO]: [WorldEdit] Loading WorldEdit v6.0;3342-78f975b9
[13:38:42 INFO]: [CardinalPGM] Loading Cardinal v1.0-SNAPSHOT-git-CardinalPGM-d844cfd
[13:38:42 INFO]: Preparing level "world"
[13:38:43 INFO]: Preparing start region for level 0 (Seed: 3493880480819380481)
[13:38:44 INFO]: Preparing spawn area: 13%
[13:38:45 INFO]: Preparing spawn area: 53%
[13:38:46 INFO]: Preparing start region for level 1 (Seed: 3493880480819380481)
[13:38:47 INFO]: Preparing spawn area: 40%
[13:38:47 INFO]: Preparing start region for level 2 (Seed: 3493880480819380481)
[13:38:48 INFO]: [WorldEdit] Enabling WorldEdit v6.0;3342-78f975b9
[13:38:48 INFO]: WEPIF: Using the Bukkit Permissions API.
[13:38:49 INFO]: [WorldEdit] Using com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_8_R1 as the Bukkit adapter
[13:38:49 INFO]: [CardinalPGM] Enabling Cardinal v1.0-SNAPSHOT-git-CardinalPGM-d844cfd
[13:38:49 WARN]: java.io.FileNotFoundException: plugins/Cardinal/database.xml (No such file or directory)
[13:38:49 WARN]: 	at java.io.FileOutputStream.open(Native Method)
[13:38:49 WARN]: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
[13:38:49 WARN]: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:171)
[13:38:49 WARN]: 	at java.io.FileWriter.<init>(FileWriter.java:90)
[13:38:49 WARN]: 	at in.twizmwaz.cardinal.Database.save(Database.java:44)
[13:38:49 WARN]: 	at in.twizmwaz.cardinal.Database.newInstance(Database.java:31)
[13:38:49 WARN]: 	at in.twizmwaz.cardinal.Cardinal.onEnable(Cardinal.java:117)
[13:38:49 WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[13:38:49 WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:327)
[13:38:49 WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
[13:38:49 WARN]: 	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:346)
[13:38:49 WARN]: 	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:318)
[13:38:49 WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.q(MinecraftServer.java:404)
[13:38:49 WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.k(MinecraftServer.java:372)
[13:38:49 WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.a(MinecraftServer.java:327)
[13:38:49 WARN]: 	at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:190)
[13:38:49 WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:490)
[13:38:49 WARN]: 	at java.lang.Thread.run(Thread.java:745)
[13:38:49 INFO]: [CardinalPGM] Deleting match files, this can be disabled via the configuration
[13:38:49 ERROR]: Error occurred while enabling Cardinal v1.0-SNAPSHOT-git-CardinalPGM-d844cfd (Is it up to date?)
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:635) ~[?:1.7.0_75]
	at java.util.ArrayList.get(ArrayList.java:411) ~[?:1.7.0_75]
	at in.twizmwaz.cardinal.rotation.Rotation.getNext(Rotation.java:143) ~[?:?]
	at in.twizmwaz.cardinal.GameHandler.<init>(GameHandler.java:31) ~[?:?]
	at in.twizmwaz.cardinal.Cardinal.onEnable(Cardinal.java:153) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[sportbukkit.jar:git-SportBukkit-715f5f8]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:327) [sportbukkit.jar:git-SportBukkit-715f5f8]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [sportbukkit.jar:git-SportBukkit-715f5f8]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:346) [sportbukkit.jar:git-SportBukkit-715f5f8]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:318) [sportbukkit.jar:git-SportBukkit-715f5f8]
	at net.minecraft.server.v1_8_R1.MinecraftServer.q(MinecraftServer.java:404) [sportbukkit.jar:git-SportBukkit-715f5f8]
	at net.minecraft.server.v1_8_R1.MinecraftServer.k(MinecraftServer.java:372) [sportbukkit.jar:git-SportBukkit-715f5f8]
	at net.minecraft.server.v1_8_R1.MinecraftServer.a(MinecraftServer.java:327) [sportbukkit.jar:git-SportBukkit-715f5f8]
	at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:190) [sportbukkit.jar:git-SportBukkit-715f5f8]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:490) [sportbukkit.jar:git-SportBukkit-715f5f8]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_75]
[13:38:49 INFO]: Server permissions file permissions.yml is empty, ignoring it
[13:38:49 INFO]: Done (6.928s)! For help, type "help" or "?"
>stop
[13:39:03 INFO]: Stopping the server
[13:39:03 INFO]: Stopping server
[13:39:03 INFO]: [CardinalPGM] Disabling Cardinal v1.0-SNAPSHOT-git-CardinalPGM-d844cfd
[13:39:03 INFO]: [WorldEdit] Disabling WorldEdit v6.0;3342-78f975b9
[13:39:03 INFO]: Saving players
[13:39:03 INFO]: Saving worlds
[13:39:03 INFO]: Saving chunks for level 'world'/Overworld
[13:39:04 INFO]: Saving chunks for level 'world_nether'/Nether
[13:39:04 INFO]: Saving chunks for level 'world_the_end'/The End
[13:39:04 INFO]: Stopping server

**Comment by SungMatt** [comment]
Use Java 8.

**Comment by dentmaged** [comment]
I think it might be because he has no maps. Can you post a screenshot of your maps folder? It should be in your server root.

**Comment by iEli2tyree011** [comment]
@SungMatt This isn't a Java issue

**Comment by Tranziii** [comment]
It's indeed empty

**Comment by iEli2tyree011** [comment]
@Tranziii You need maps for Cardinal to work.

**Comment by AngelCasillas01** [comment]
@iEli2tyree011 Were do you find them

**Comment by Tranziii** [comment]
I've placed  a map but same log

**Comment by iEli2tyree011** [comment]
What is inside the map that you added, and where did you put the map?

**Comment by Tranziii** [comment]
Region, XML and level.dat.  I placed the map in the maps folder

**Comment by iEli2tyree011** [comment]
@Tranziii Can you try restarting your server and posting the latest logs?

**Comment by Tranziii** [comment]
[15:07:20 INFO]: Starting minecraft server version 1.8
[15:07:20 INFO]: Loading properties
[15:07:20 INFO]: Default game type: SURVIVAL
[15:07:20 INFO]: Generating keypair
[15:07:20 INFO]: Starting Minecraft server on *:25565
[15:07:21 INFO]: This server is running SportBukkit version git-SportBukkit-715f5f8 (MC: 1.8) (Implementing API version 1.8-R0.1-SNAPSHOT)
[15:07:21 INFO]: [WorldEdit] Loading WorldEdit v6.0;3342-78f975b9
[15:07:21 INFO]: [CardinalPGM] Loading Cardinal v1.0-SNAPSHOT-git-CardinalPGM-d844cfd
[15:07:21 INFO]: Preparing level "world"
[15:07:22 INFO]: Preparing start region for level 0 (Seed: 3493880480819380481)
[15:07:23 INFO]: Preparing spawn area: 2%
[15:07:24 INFO]: Preparing spawn area: 25%
[15:07:25 INFO]: Preparing spawn area: 31%
[15:07:26 INFO]: Preparing spawn area: 38%
[15:07:27 INFO]: Preparing spawn area: 58%
[15:07:28 INFO]: Preparing spawn area: 97%
[15:07:28 INFO]: Preparing start region for level 1 (Seed: 3493880480819380481)
[15:07:29 INFO]: Preparing spawn area: 80%
[15:07:30 INFO]: Preparing start region for level 2 (Seed: 3493880480819380481)
[15:07:30 INFO]: [WorldEdit] Enabling WorldEdit v6.0;3342-78f975b9
[15:07:31 INFO]: WEPIF: Using the Bukkit Permissions API.
[15:07:31 INFO]: [WorldEdit] Using com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_8_R1 as the Bukkit adapter
[15:07:31 INFO]: [CardinalPGM] Enabling Cardinal v1.0-SNAPSHOT-git-CardinalPGM-d844cfd
[15:07:31 INFO]: [CardinalPGM] Deleting match files, this can be disabled via the configuration
[15:07:31 WARN]: Failed to load map at /Users/Gian/Desktop/Project Ares/maps/Kytriak
[15:07:31 ERROR]: Error occurred while enabling Cardinal v1.0-SNAPSHOT-git-CardinalPGM-d844cfd (Is it up to date?)
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:635) ~[?:1.7.0_75]
	at java.util.ArrayList.get(ArrayList.java:411) ~[?:1.7.0_75]
	at in.twizmwaz.cardinal.rotation.Rotation.getNext(Rotation.java:143) ~[?:?]
	at in.twizmwaz.cardinal.GameHandler.<init>(GameHandler.java:31) ~[?:?]
	at in.twizmwaz.cardinal.Cardinal.onEnable(Cardinal.java:153) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[sportbukkit.jar:git-SportBukkit-715f5f8]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:327) [sportbukkit.jar:git-SportBukkit-715f5f8]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [sportbukkit.jar:git-SportBukkit-715f5f8]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:346) [sportbukkit.jar:git-SportBukkit-715f5f8]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:318) [sportbukkit.jar:git-SportBukkit-715f5f8]
	at net.minecraft.server.v1_8_R1.MinecraftServer.q(MinecraftServer.java:404) [sportbukkit.jar:git-SportBukkit-715f5f8]
	at net.minecraft.server.v1_8_R1.MinecraftServer.k(MinecraftServer.java:372) [sportbukkit.jar:git-SportBukkit-715f5f8]
	at net.minecraft.server.v1_8_R1.MinecraftServer.a(MinecraftServer.java:327) [sportbukkit.jar:git-SportBukkit-715f5f8]
	at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:190) [sportbukkit.jar:git-SportBukkit-715f5f8]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:490) [sportbukkit.jar:git-SportBukkit-715f5f8]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_75]

**Comment by iEli2tyree011** [comment]
Can you try adding the name of the map (the name in the map.xml) to the rotation.txt file?

**Comment by AngelCasillas01** [comment]
@iEli2tyree011 Isn't creating by default?

**Comment by iEli2tyree011** [comment]
@AngelCasillas01 Only if the file is not already there. Since he started the server without any maps, the rotation file was generated, but was blank. But when he added a map, it still wasn't updated, because the file already existed.

**Comment by Tranziii** [comment]
[15:10:44 INFO]: Starting minecraft server version 1.8
[15:10:44 INFO]: Loading properties
[15:10:44 INFO]: Default game type: SURVIVAL
[15:10:44 INFO]: Generating keypair
[15:10:45 INFO]: Starting Minecraft server on *:25565
[15:10:46 INFO]: This server is running SportBukkit version git-SportBukkit-715f5f8 (MC: 1.8) (Implementing API version 1.8-R0.1-SNAPSHOT)
[15:10:46 INFO]: [WorldEdit] Loading WorldEdit v6.0;3342-78f975b9
[15:10:46 INFO]: [CardinalPGM] Loading Cardinal v1.0-SNAPSHOT-git-CardinalPGM-d844cfd
[15:10:46 INFO]: Preparing level "world"
[15:10:46 INFO]: Preparing start region for level 0 (Seed: 3493880480819380481)
[15:10:47 INFO]: Preparing spawn area: 10%
[15:10:49 INFO]: Preparing spawn area: 33%
[15:10:50 INFO]: Preparing spawn area: 85%
[15:10:50 INFO]: Preparing start region for level 1 (Seed: 3493880480819380481)
[15:10:51 INFO]: Preparing spawn area: 21%
[15:10:52 INFO]: Preparing spawn area: 92%
[15:10:52 INFO]: Preparing start region for level 2 (Seed: 3493880480819380481)
[15:10:53 INFO]: [WorldEdit] Enabling WorldEdit v6.0;3342-78f975b9
[15:10:53 INFO]: WEPIF: Using the Bukkit Permissions API.
[15:10:54 INFO]: [WorldEdit] Using com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_8_R1 as the Bukkit adapter
[15:10:54 INFO]: [CardinalPGM] Enabling Cardinal v1.0-SNAPSHOT-git-CardinalPGM-d844cfd
[15:10:54 INFO]: [CardinalPGM] Deleting match files, this can be disabled via the configuration
[15:10:54 WARN]: Failed to load map at /Users/Gian/Desktop/Project Ares/maps/Kytriak
[15:10:54 ERROR]: Error occurred while enabling Cardinal v1.0-SNAPSHOT-git-CardinalPGM-d844cfd (Is it up to date?)
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:635) ~[?:1.7.0_75]
	at java.util.ArrayList.get(ArrayList.java:411) ~[?:1.7.0_75]
	at in.twizmwaz.cardinal.rotation.Rotation.getNext(Rotation.java:143) ~[?:?]
	at in.twizmwaz.cardinal.GameHandler.<init>(GameHandler.java:31) ~[?:?]
	at in.twizmwaz.cardinal.Cardinal.onEnable(Cardinal.java:153) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[sportbukkit.jar:git-SportBukkit-715f5f8]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:327) [sportbukkit.jar:git-SportBukkit-715f5f8]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [sportbukkit.jar:git-SportBukkit-715f5f8]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:346) [sportbukkit.jar:git-SportBukkit-715f5f8]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:318) [sportbukkit.jar:git-SportBukkit-715f5f8]
	at net.minecraft.server.v1_8_R1.MinecraftServer.q(MinecraftServer.java:404) [sportbukkit.jar:git-SportBukkit-715f5f8]
	at net.minecraft.server.v1_8_R1.MinecraftServer.k(MinecraftServer.java:372) [sportbukkit.jar:git-SportBukkit-715f5f8]
	at net.minecraft.server.v1_8_R1.MinecraftServer.a(MinecraftServer.java:327) [sportbukkit.jar:git-SportBukkit-715f5f8]
	at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:190) [sportbukkit.jar:git-SportBukkit-715f5f8]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:490) [sportbukkit.jar:git-SportBukkit-715f5f8]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_75]
[15:10:54 INFO]: Server permissions file permissions.yml is empty, ignoring it
[15:10:54 INFO]: Done (8.372s)! For help, type "help" or "?"

It keeps saying failed to load map

**Comment by dentmaged** [comment]
I would delete the rotations.txt file.

**Comment by Tranziii** [comment]
How can I correctly load the map and what should I place in the maps folder

**Comment by SungMatt** [comment]
@Tranziii Here is an [example](https://github.com/SungMatt/CardinalPGMDemo) of how your server directory should look like.

**Comment by twizmwazin** [comment]
@Tranziii In the log, it clearly states that the map "Kytriak" is not loading. The XML may be invalid.

**Comment by iEli2tyree011** [comment]
@Tranziii Can you pastebin the text inside of `maps.xml`?

**Comment by iEli2tyree011** [comment]
Closing due to no response and this is only due to incorrectly setting up the server. The XML is not valid, which means the plugin can't even read it, it's not even having issues parsing it.
