### ISSUE TITLE
Error on MatchStartEvent

### ISSUE THREAD

**Issue by TeamDDG** [twizmwazin/CardinalPGM#618]
[00:44:14 ERROR]: Could not pass event MatchStartEvent to Cardinal v1.0-SNAPSHOT-git-CardinalPGM-18a0ea8
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:297) ~[bukkit.jar:git-SportBukkit-dd90420]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[bukkit.jar:git-SportBukkit-dd90420]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [bukkit.jar:git-SportBukkit-dd90420]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [bukkit.jar:git-SportBukkit-dd90420]
        at in.twizmwaz.cardinal.module.modules.startTimer.StartTimer.run(StartTimer.java:60) [CardinalPGM-1.0-SNAPSHOT%20(9).jar:?]
        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:53) [bukkit.jar:git-SportBukkit-dd90420]
        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349) [bukkit.jar:git-SportBukkit-dd90420]
        at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:666) [bukkit.jar:git-SportBukkit-dd90420]
        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:284) [bukkit.jar:git-SportBukkit-dd90420]
        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:611) [bukkit.jar:git-SportBukkit-dd90420]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:521) [bukkit.jar:git-SportBukkit-dd90420]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(Unknown Source) ~[?:1.8.0_45]
        at java.util.ArrayList.get(Unknown Source) ~[?:1.8.0_45]
        at in.twizmwaz.cardinal.module.ModuleCollection.getRandom(ModuleCollection.java:70) ~[?:?]
        at in.twizmwaz.cardinal.module.modules.respawn.RespawnModule.onMatchStart(RespawnModule.java:137) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:295) ~[bukkit.jar:git-SportBukkit-dd90420]
        ... 11 more

**Comment by ryanw-ny** [comment]
@TeamDDG No need to add the [BUG] tag it will be added by the developers if this is a valid issue.

**Comment by TeamDDG** [comment]
sorry

**Comment by CaptainElliott** [comment]
Is the map valid? It looks like there are no loaded modules

**Comment by iEli2tyree011** [comment]
@CaptainElliott It would mean there's no valid spawns for a certain team

**Comment by TeamDDG** [comment]
i have Loaded 27 maps
and 3 maps it crashes ( Golden Drought 1 and 2 ) and Ring Race

**Comment by SungMatt** [comment]
@TeamDDG could you pastebin the XMLs for the crashes maps?

**Comment by TeamDDG** [comment]
http://pastebin.com/YJPffrYu   ((RingRace))
http://pastebin.com/Mk0CP6mL  ((Golden Drought))
http://pastebin.com/7vcV2MNr ((Golden Drought 2))

**Comment by ryanw-ny** [comment]
@TeamDDG You have multiple </spawns> tags

**Comment by CaptainElliott** [comment]
@ryanw-ny that is not invalid, the extra one is applying a kit to both teams

**Comment by TiTo-418** [comment]
Try with these XMLs:
[Golden Drought](view-source:https://maps.oc.tc/CTW/Standard/Golden%20Drought/map.xml)
[Golden Drought II](view-source:https://maps.oc.tc/CTW/Standard/Golden%20Drought%20II/map.xml)
[Ring Race](view-source:https://maps.oc.tc/CTW/Standard/Ring%20Race/map.xml)

**Comment by twizmwazin** [comment]
Closing as this doesn't seem to be a valid issue
