### ISSUE TITLE
¿Why i get that error?

### ISSUE THREAD

**Issue by ElFlambMC** [twizmwazin/CardinalPGM#642]
I get this error http://pastebin.com/NA69b2bd
The latest version.

**Comment by ElFlambMC** [comment]
And this stop my server : [22:10:40] [Server thread/ERROR]: Exception stopping the server
net.minecraft.server.v1_8_R1.ExceptionWorldConflict: Failed to check session lock, aborting
	at net.minecraft.server.v1_8_R1.WorldNBTStorage.checkSession(WorldNBTStorage.java:79) ~[minecraft_server.jar:git-SportBukkit-eb28670]
	at net.minecraft.server.v1_8_R1.World.checkSession(World.java:2630) ~[minecraft_server.jar:git-SportBukkit-eb28670]
	at net.minecraft.server.v1_8_R1.WorldServer.a(WorldServer.java:896) ~[minecraft_server.jar:git-SportBukkit-eb28670]
	at net.minecraft.server.v1_8_R1.WorldServer.save(WorldServer.java:868) ~[minecraft_server.jar:git-SportBukkit-eb28670]
	at net.minecraft.server.v1_8_R1.MinecraftServer.saveChunks(MinecraftServer.java:419) ~[minecraft_server.jar:git-SportBukkit-eb28670]
	at net.minecraft.server.v1_8_R1.MinecraftServer.stop(MinecraftServer.java:447) ~[minecraft_server.jar:git-SportBukkit-eb28670]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:550) [minecraft_server.jar:git-SportBukkit-eb28670]
	at java.lang.Thread.run(Unknown Source) [?:1.7.0_09]
[22:10:40] [Thread-4/INFO]: Stopping server

**Comment by twizmwazin** [comment]
You have a broken map file, and "latest version" is so useless.
