### ISSUE TITLE
cycle and gamehandler error

### ISSUE THREAD

**Issue by RubeVi** [twizmwazin/CardinalPGM#676]
I don't change anything. This is the log.

[18:43:28 INFO]: Server permissions file permissions.yml is empty, ignoring it
[18:43:29 INFO]: Done (10.223s)! For help, type "help" or "?"
[18:43:31 INFO]: World matches/6dcc7a07-e0de-4924-ae1b-90f8fee274e9 is a duplica
te of another world and has been prevented from loading. Please delete the uid.d
at file from matches/6dcc7a07-e0de-4924-ae1b-90f8fee274e9's world directory if y
ou want to be able to load the duplicate world.
[18:43:31 ERROR]: [CardinalPGM] Task #3 for Cardinal v1.0-SNAPSHOT-git-CardinalP
GM-00756e5 generated an exception
java.lang.NullPointerException
        at in.twizmwaz.cardinal.cycle.Cycle.run(Cycle.java:43) ~[?:?]
        at in.twizmwaz.cardinal.GameHandler.cycleAndMakeMatch(GameHandler.java:4
9) ~[?:?]
        at in.twizmwaz.cardinal.GameHandler$1.run(GameHandler.java:36) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java
:53) ~[SportBukkit.jar:git-SportBukkit-6506b33]
        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftScheduler.mainThreadHea
rtbeat(CraftScheduler.java:349) [SportBukkit.jar:git-SportBukkit-6506b33]
        at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:6
66) [SportBukkit.jar:git-SportBukkit-6506b33]
        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:2
84) [SportBukkit.jar:git-SportBukkit-6506b33]
        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:6
11) [SportBukkit.jar:git-SportBukkit-6506b33]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java
:521) [SportBukkit.jar:git-SportBukkit-6506b33]
        at java.lang.Thread.run(Unknown Source) [?:1.7.0_75]

**Comment by TiTo-418** [comment]
World matches/6dcc7a07-e0de-4924-ae1b-90f8fee274e9 is a duplica
te of another world and has been prevented from loading. Please delete the uid.d
at file from matches/6dcc7a07-e0de-4924-ae1b-90f8fee274e9's world directory if y
ou want to be able to load the duplicate world.

**Comment by RubeVi** [comment]
no pasa nada :|

**Comment by twizmwazin** [comment]
You need to remove unnecessary files from your map repository. `uid.dat` will cause world loading to fail.

**Comment by RubeVi** [comment]
thanks
