### ISSUE TITLE
inconsistency with tab header names and cycled maps descriptions

### ISSUE THREAD

**Issue by Pablete1234** [twizmwazin/CardinalPGM#736]
differences in maps:
http://gyazo.com/16831d004a9511bc733e2a72cd454ffc

maps with correct color get player "null", and the maps that for some reason load with old color, have the name right (both maps use UUID's on their xml's)
the difference is that fractal (name = null) uses:
```<author uuid="dbe909c6-2b15-4528-b12a-c77ed4031496" contribution="Design and building"/>```
and Golden Drought III uses:
```<author uuid="459fd919-0d58-401a-9601-6cab1eb721ab"/>```

also this http://gyazo.com/21973f36ca69a00d391fb711720acaeb should have the new names

ps:
also adding to this, if the map creator is in the game, they will always be displayed as the name they had on the last match (joined red or blue or obs from the last match), because that only gets set on map load, not on player joining teams event

**Comment by Pablete1234** [comment]
Some more on this :
from what i've seen:
it only uses the new names if there are collaborators
ocasionally it does work and displays new names correclty

**Comment by twizmwazin** [comment]
I wrote the original system for this, and if I recall correctly, what I ended up doing is fetching player names by UUIDs using Moajng's API, and then storing them permanently. I stored them because Mojang's API has a 600 requests cap every 10 minutes, and so only 600 usernames can be grabbed. null shows up when it could get the name, and it will use old names because once it gets a name, it never again checks for an updated name. OCN gets around the 600 request limit by storing UUIDs and player names in their own databases, presumably. When a player logs onto Overcast, it updates their databases, and in return the displayed names for maps. Because many map makers won't be joining every scrim server frequently, I can't follow this same approach in Cardinal, unless I kept a public repository somewhere, although it would likely get vandalized.

**Comment by SungMatt** [comment]
@twizmwazin This is update is invoked when the server starts right?

**Comment by Pablete1234** [comment]
How about storing the UUID's + player names along with a time mark (for example 24h), if the last time checked was more than 24 hours ago, then check again, unless you have passed the 600 request cap, then you have to use the old one

**Comment by twizmwazin** [comment]
@Pablete1234 Feel free to make a PR

**Comment by Pablete1234** [comment]
@twizmwazin i'm not that good with java, i can understeand it and writte basic code (you saw how i prevented /tp outside), but definetly i'm not an experienced programmer

**Comment by Pablete1234** [comment]
@twizmwazin now that i think of it, to get the first names you should use mojang's api, but to update the names you may want to use oc.tc/oldname, and that redirects to oc.tc/newname, maybe?

**Comment by twizmwazin** [comment]
@Pablete1234 Moajng's API gives a fill username history on a single request.

**Comment by Pablete1234** [comment]
@twizmwazin I know how mojang's api work, but you said that there is a 600 request limit, maybe that's a way to go arround

**Comment by twizmwazin** [comment]
@Pablete1234 The best way would be to regularly check for updates, on a schedule.

**Comment by Pablete1234** [comment]
but as it is right now, why do I always get "null" map authors, what is filling that 600 cap?

**Comment by CaptainElliott** [comment]
600 different authors/contributors have been requested

**Comment by Pablete1234** [comment]
Just as I start the server the first map that loads already has authors "null"

**Comment by TiTo-418** [comment]
```
[00:18:52] [Server thread/WARN]: Couldn't look up profile properties for com.mojang.authlib.GameProfile@2a206a9c[id=91295196-9cd2-4963-b7ec-afd1a110edbe,name=Pbat,properties={},legacy=false]
com.mojang.authlib.exceptions.AuthenticationException: The client has sent too many requests within a certain amount of time
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:65) ~[custom_server.jar:git-Bukkit-0a11d75]
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:175) [custom_server.jar:git-Bukkit-0a11d75]
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:168) [custom_server.jar:git-Bukkit-0a11d75]
	at net.minecraft.server.v1_8_R3.TileEntitySkull.b(TileEntitySkull.java:92) [custom_server.jar:git-Bukkit-0a11d75]
	at net.minecraft.server.v1_8_R3.TileEntitySkull.e(TileEntitySkull.java:71) [custom_server.jar:git-Bukkit-0a11d75]
	at net.minecraft.server.v1_8_R3.TileEntitySkull.a(TileEntitySkull.java:41) [custom_server.jar:git-Bukkit-0a11d75]
	at net.minecraft.server.v1_8_R3.TileEntity.c(TileEntity.java:79) [custom_server.jar:git-Bukkit-0a11d75]
	at net.minecraft.server.v1_8_R3.ChunkRegionLoader.loadEntities(ChunkRegionLoader.java:414) [custom_server.jar:git-Bukkit-0a11d75]
	at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:46) [custom_server.jar:git-Bukkit-0a11d75]
	at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:1) [custom_server.jar:git-Bukkit-0a11d75]
	at org.bukkit.craftbukkit.v1_8_R3.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:337) [custom_server.jar:git-Bukkit-0a11d75]
	at org.bukkit.craftbukkit.v1_8_R3.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:295) [custom_server.jar:git-Bukkit-0a11d75]
	at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:16) [custom_server.jar:git-Bukkit-0a11d75]
	at net.minecraft.server.v1_8_R3.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:115) [custom_server.jar:git-Bukkit-0a11d75]
	at net.minecraft.server.v1_8_R3.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:97) [custom_server.jar:git-Bukkit-0a11d75]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.createWorld(CraftServer.java:970) [custom_server.jar:git-Bukkit-0a11d75]
	at org.bukkit.Bukkit.createWorld(Bukkit.java:518) [custom_server.jar:git-Bukkit-0a11d75]
	at org.bukkit.WorldCreator.createWorld(WorldCreator.java:271) [custom_server.jar:git-Bukkit-0a11d75]
	at in.twizmwaz.cardinal.cycle.Cycle.run(Cycle.java:42) [CardinalPGM-1.0-SNAPSHOT%20(86).jar:?]
	at in.twizmwaz.cardinal.GameHandler.cycleAndMakeMatch(GameHandler.java:51) [CardinalPGM-1.0-SNAPSHOT%20(86).jar:?]
	at in.twizmwaz.cardinal.GameHandler$1.run(GameHandler.java:36) [CardinalPGM-1.0-SNAPSHOT%20(86).jar:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:53) [custom_server.jar:git-Bukkit-0a11d75]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349) [custom_server.jar:git-Bukkit-0a11d75]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:696) [custom_server.jar:git-Bukkit-0a11d75]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:335) [custom_server.jar:git-Bukkit-0a11d75]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:645) [custom_server.jar:git-Bukkit-0a11d75]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:555) [custom_server.jar:git-Bukkit-0a11d75]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_51]
```
