### ISSUE TITLE
 CardinalPGM and Sportbukkit are not supported.

### ISSUE THREAD

**Issue by PizzaGatoo** [twizmwazin/CardinalPGM#957]
Hi. I have a server scrimmages, which is very outdated, so I decided to upgrade it, the issue is that the cardinalpgm and sportbukkit are not compatible, I downloaded many cardinal and sportbukkit, sportbukkit I have downloaded the latest version (1.8.7) and the cardinal of the latest version, but it doesn't work. Someone help me? Please . Thank you

**Comment by TiTo-418** [comment]
Logs?

**Comment by PizzaGatoo** [comment]
[18:24:05] [Server thread/INFO]: Starting minecraft server version 1.8.7
[18:24:05] [Server thread/INFO]: Loading properties
[18:24:05] [Server thread/INFO]: Default game type: SURVIVAL
[18:24:05] [Server thread/INFO]: Generating keypair
[18:24:06] [Server thread/INFO]: Starting Minecraft server on 5.39.49.1:25861
[18:24:06] [Server thread/INFO]: Using epoll channel type
[18:24:06] [Server thread/INFO]: This server is running SportBukkit version git-Bukkit-4af66b3 (MC: 1.8.7) (Implementing API version 1.8.7-R0.1-SNAPSHOT)
[18:24:06] [Server thread/ERROR]: Could not load 'plugins/CardinalPGM-1.0-SNAPSHOT.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:173) ~[sportbukkit.jar:git-Bukkit-4af66b3]
at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [sportbukkit.jar:git-Bukkit-4af66b3]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:295) [sportbukkit.jar:git-Bukkit-4af66b3]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.(CraftServer.java:257) [sportbukkit.jar:git-Bukkit-4af66b3]
at net.minecraft.server.v1_8_R3.PlayerList.(PlayerList.java:71) [sportbukkit.jar:git-Bukkit-4af66b3]
at net.minecraft.server.v1_8_R3.DedicatedPlayerList.(SourceFile:14) [sportbukkit.jar:git-Bukkit-4af66b3]
at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:179) [sportbukkit.jar:git-Bukkit-4af66b3]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:524) [sportbukkit.jar:git-Bukkit-4af66b3]
at java.lang.Thread.run(Thread.java:722) [?:1.7.0_03]
Caused by: java.util.zip.ZipException: error in opening zip file
at java.util.zip.ZipFile.open(Native Method) ~[?:1.7.0_03]
at java.util.zip.ZipFile.(ZipFile.java:214) ~[?:1.7.0_03]
at java.util.zip.ZipFile.(ZipFile.java:144) ~[?:1.7.0_03]
at java.util.jar.JarFile.(JarFile.java:152) ~[?:1.7.0_03]
at java.util.jar.JarFile.(JarFile.java:116) ~[?:1.7.0_03]
at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:161) ~[sportbukkit.jar:git-Bukkit-4af66b3]
... 8 more
[18:24:06] [Server thread/ERROR]: Could not load 'plugins/ClusterAPI-0.1.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: me/AdityaTD/ClusterAPI/Main : Unsupported major.minor version 52.0
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:140) ~[sportbukkit.jar:git-Bukkit-4af66b3]
at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:328) ~[sportbukkit.jar:git-Bukkit-4af66b3]
at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [sportbukkit.jar:git-Bukkit-4af66b3]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:295) [sportbukkit.jar:git-Bukkit-4af66b3]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.(CraftServer.java:257) [sportbukkit.jar:git-Bukkit-4af66b3]
at net.minecraft.server.v1_8_R3.PlayerList.(PlayerList.java:71) [sportbukkit.jar:git-Bukkit-4af66b3]
at net.minecraft.server.v1_8_R3.DedicatedPlayerList.(SourceFile:14) [sportbukkit.jar:git-Bukkit-4af66b3]
at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:179) [sportbukkit.jar:git-Bukkit-4af66b3]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:524) [sportbukkit.jar:git-Bukkit-4af66b3]
at java.lang.Thread.run(Thread.java:722) [?:1.7.0_03]
Caused by: java.lang.UnsupportedClassVersionError: me/AdityaTD/ClusterAPI/Main : Unsupported major.minor version 52.0
at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.7.0_03]
at java.lang.ClassLoader.defineClass(ClassLoader.java:791) ~[?:1.7.0_03]
at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.7.0_03]
at java.net.URLClassLoader.defineClass(URLClassLoader.java:449) ~[?:1.7.0_03]
at java.net.URLClassLoader.access$100(URLClassLoader.java:71) ~[?:1.7.0_03]
at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[?:1.7.0_03]
at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[?:1.7.0_03]
at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_03]
at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[?:1.7.0_03]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:82) ~[sportbukkit.jar:git-Bukkit-4af66b3]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:67) ~[sportbukkit.jar:git-Bukkit-4af66b3]
at java.lang.ClassLoader.loadClass(ClassLoader.java:423) ~[?:1.7.0_03]
at java.lang.ClassLoader.loadClass(ClassLoader.java:356) ~[?:1.7.0_03]
at java.lang.Class.forName0(Native Method) ~[?:1.7.0_03]
at java.lang.Class.forName(Class.java:264) ~[?:1.7.0_03]
at org.bukkit.plugin.java.PluginClassLoader.(PluginClassLoader.java:45) ~[sportbukkit.jar:git-Bukkit-4af66b3]
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:136) ~[sportbukkit.jar:git-Bukkit-4af66b3]
... 9 more
[18:24:06] [Server thread/INFO]: [TitleWelcomeMessage] Loading TitleWelcomeMessage v3.0
[18:24:06] [Server thread/INFO]: [WorldEdit] Loading WorldEdit v6.1;no_git_id
[18:24:06] [Server thread/INFO]: [PingPlayer] Loading PingPlayer v1.3.0
[18:24:06] [Server thread/INFO]: [Commandspy] Loading Commandspy v3.2.0
[18:24:06] [Server thread/INFO]: Preparing level "world"
[18:24:06] [Server thread/INFO]: Preparing start region for level 0 (Seed: 3624949765980612445)
[18:24:06] [Server thread/INFO]: Preparing start region for level 1 (Seed: 3624949765980612445)
[18:24:07] [Server thread/INFO]: Preparing start region for level 2 (Seed: 3624949765980612445)
[18:24:07] [Server thread/INFO]: [TitleWelcomeMessage] Enabling TitleWelcomeMessage v3.0
[18:24:07] [Server thread/INFO]: [m
[18:24:07] [Server thread/INFO]: [0;34;1m-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-[m
[18:24:07] [Server thread/INFO]: [m
[18:24:07] [Server thread/INFO]: [0;36;1m Title Welcome Message[m
[18:24:07] [Server thread/INFO]: [0;36;1m Version 3.0[m
[18:24:07] [Server thread/INFO]: [0;31;1m YouTube: http://bit.ly/ATDYouTube[m
[18:24:07] [Server thread/INFO]: [m
[18:24:07] [Server thread/INFO]: [0;34;1m-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-[m
[18:24:07] [Server thread/INFO]: [WorldEdit] Enabling WorldEdit v6.1;no_git_id
[18:24:08] [Server thread/INFO]: WEPIF: Using the Bukkit Permissions API.
[18:24:08] [Server thread/INFO]: [WorldEdit] Using com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_8_R3 as the Bukkit adapter
[18:24:08] [Server thread/INFO]: [PingPlayer] Enabling PingPlayer v1.3.0
[18:24:08] [Server thread/INFO]: [PingPlayer] Thank you for enabling Metrics!
[18:24:08] [Server thread/INFO]: [PingPlayer] PingPlayer v1.3.0 enabled.
[18:24:08] [Server thread/INFO]: [Commandspy] Enabling Commandspy v3.2.0
[18:24:08] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[18:24:08] [Server thread/INFO]: Done (1.936s)! For help, type "help" or "?"
[18:24:08] [Server thread/INFO]: Starting GS4 status listener
[18:24:08] [Server thread/INFO]: Starting remote control listener
[18:24:08] [Query Listener #1/INFO]: Query running on 5.39.49.1:25861
[18:24:08] [Server thread/WARN]: No rcon password set in '/home/alexruiz1/31323/server.properties', rcon disabled!
[18:24:08] [Server thread/INFO]: Unknown command. Type "help" for help.[m

**Comment by CaptainElliott** [comment]
You've modified the plugin?

**Comment by PizzaGatoo** [comment]
No, I have not changed anything. :c  But not if it is for the other plugins that are outdated or something.

**Comment by CaptainElliott** [comment]
remove all other plugins and make sure to clone the latest version

**Comment by twizmwazin** [comment]
The plugin.yml file is invalid. You cannot export using eclipse, you need to build the project using maven. Instructions are on the wiki. Alternatively, you can always download the latest version from http://ci.twizmwaz.in/job/Cardinal/lastSuccessfulBuild/

**Comment by elephantLocator** [comment]
I'm getting this error too, and I'm using the most recent download. Any ideas where I've gone wrong? Also using most recent version of SportBukkit,

**Comment by SwiftGFX** [comment]
Did you checked plugins' file size? I think that download wasn't successful...

**Comment by elephantLocator** [comment]
@SwiftGFX ah, that looks like a possibility actually, thanks!

**Comment by Alfalik** [comment]
I've had problems starting my server. Had to delete ´´´plugin.yml´´´ and ´´´database.xml´´´, both were causing error. Hope this help.
